services:

  # User Service con integración de logs
  user-service:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@user-db:5432/users
      - LOGSTASH_HOST=logstash:5044
    depends_on:
      user-db:
        condition: service_healthy
    volumes:
      - .:/app  
      - /app/node_modules  
      - logstash
    command: ["sh", "-c", "npx prisma migrate deploy && npm run dev"]

  # Base de datos PostgreSQL
  user-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Caché
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Elasticsearch: Base de datos para logs
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  # Kibana: Interfaz para visualizar logs
  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  # Logstash: Procesador de logs
  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"

volumes:
  user_data:
