services:

  # User Service con integración de logs
  user-service:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@user-db:5432/users
      - LOGSTASH_HOST=logstash:5044
    depends_on:
      user-db:
        condition: service_healthy
    volumes:
      - .:/app  
      - /app/node_modules  
      - logstash
    command: ["sh", "-c", "npx prisma migrate deploy && npm run dev"]

  # Base de datos PostgreSQL
  user-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Caché
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  user_data:
